#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Run e-uae emulator with some configuration goodies :)
"""

from e_uae_wrapper import wrapper


def main():
    """run wrapper"""
    wrapper.run()


if __name__ == "__main__":
    main()
